export type FoodItem = { name: string; kcalPer100g: number; category: string };

export const FOODS: FoodItem[] = [
  // Cereali e derivati
  { name: "Pasta (cruda)", kcalPer100g: 353, category: "Cereali" },
  { name: "Pasta (cotta)", kcalPer100g: 131, category: "Cereali" },
  { name: "Pasta integrale (cruda)", kcalPer100g: 337, category: "Cereali" },
  { name: "Pasta integrale (cotta)", kcalPer100g: 124, category: "Cereali" },
  { name: "Riso bianco (crudo)", kcalPer100g: 360, category: "Cereali" },
  { name: "Riso bianco (cotto)", kcalPer100g: 130, category: "Cereali" },
  { name: "Riso integrale (crudo)", kcalPer100g: 350, category: "Cereali" },
  { name: "Riso integrale (cotto)", kcalPer100g: 123, category: "Cereali" },
  { name: "Riso basmati (cotto)", kcalPer100g: 121, category: "Cereali" },
  { name: "Pane bianco", kcalPer100g: 267, category: "Cereali" },
  { name: "Pane integrale", kcalPer100g: 247, category: "Cereali" },
  { name: "Pane di segale", kcalPer100g: 259, category: "Cereali" },
  { name: "Pane ai cereali", kcalPer100g: 263, category: "Cereali" },
  { name: "Pancarrè", kcalPer100g: 270, category: "Cereali" },
  { name: "Grissini", kcalPer100g: 390, category: "Cereali" },
  { name: "Crackers", kcalPer100g: 432, category: "Cereali" },
  { name: "Fette biscottate", kcalPer100g: 383, category: "Cereali" },
  { name: "Fette biscottate integrali", kcalPer100g: 360, category: "Cereali" },
  { name: "Corn flakes", kcalPer100g: 370, category: "Cereali" },
  { name: "Fiocchi d'avena", kcalPer100g: 379, category: "Cereali" },
  { name: "Muesli", kcalPer100g: 365, category: "Cereali" },
  { name: "Cous cous (cotto)", kcalPer100g: 112, category: "Cereali" },
  { name: "Farro (cotto)", kcalPer100g: 170, category: "Cereali" },
  { name: "Orzo perlato (cotto)", kcalPer100g: 123, category: "Cereali" },
  { name: "Quinoa (cotta)", kcalPer100g: 120, category: "Cereali" },
  { name: "Miglio (cotto)", kcalPer100g: 119, category: "Cereali" },
  { name: "Polenta (cotta)", kcalPer100g: 79, category: "Cereali" },
  { name: "Piadina", kcalPer100g: 290, category: "Cereali" },
  { name: "Pizza margherita", kcalPer100g: 271, category: "Cereali" },
  { name: "Focaccia", kcalPer100g: 280, category: "Cereali" },
  { name: "Tortilla di grano", kcalPer100g: 306, category: "Cereali" },
  { name: "Farina 00", kcalPer100g: 364, category: "Cereali" },
  { name: "Farina integrale", kcalPer100g: 339, category: "Cereali" },
  // Carne
  { name: "Petto di pollo", kcalPer100g: 110, category: "Carne" },
  { name: "Coscia di pollo", kcalPer100g: 200, category: "Carne" },
  { name: "Pollo arrosto", kcalPer100g: 184, category: "Carne" },
  { name: "Petto di tacchino", kcalPer100g: 104, category: "Carne" },
  { name: "Fesa di tacchino", kcalPer100g: 107, category: "Carne" },
  { name: "Manzo (bistecca)", kcalPer100g: 217, category: "Carne" },
  { name: "Macinato di manzo", kcalPer100g: 254, category: "Carne" },
  { name: "Macinato di tacchino", kcalPer100g: 156, category: "Carne" },
  { name: "Hamburger (carne bovina)", kcalPer100g: 295, category: "Carne" },
  { name: "Lombata di maiale", kcalPer100g: 169, category: "Carne" },
  { name: "Costine di maiale", kcalPer100g: 280, category: "Carne" },
  { name: "Agnello (coscia)", kcalPer100g: 191, category: "Carne" },
  { name: "Prosciutto cotto", kcalPer100g: 215, category: "Carne" },
  { name: "Prosciutto crudo", kcalPer100g: 259, category: "Carne" },
  { name: "Bresaola", kcalPer100g: 175, category: "Carne" },
  { name: "Salame", kcalPer100g: 336, category: "Carne" },
  { name: "Salsiccia", kcalPer100g: 305, category: "Carne" },
  { name: "Pancetta", kcalPer100g: 337, category: "Carne" },
  { name: "Mortadella", kcalPer100g: 311, category: "Carne" },
  { name: "Wurstel", kcalPer100g: 277, category: "Carne" },
  { name: "Speck", kcalPer100g: 295, category: "Carne" },
  { name: "Coppa", kcalPer100g: 340, category: "Carne" },
  { name: "Nduja", kcalPer100g: 394, category: "Carne" },
  { name: "Carpaccio di manzo", kcalPer100g: 133, category: "Carne" },
  // Pesce e frutti di mare
  { name: "Tonno in scatola (al naturale)", kcalPer100g: 103, category: "Pesce" },
  { name: "Tonno in scatola (all'olio)", kcalPer100g: 198, category: "Pesce" },
  { name: "Salmone", kcalPer100g: 208, category: "Pesce" },
  { name: "Salmone affumicato", kcalPer100g: 174, category: "Pesce" },
  { name: "Orata", kcalPer100g: 121, category: "Pesce" },
  { name: "Branzino", kcalPer100g: 97, category: "Pesce" },
  { name: "Merluzzo", kcalPer100g: 82, category: "Pesce" },
  { name: "Sgombro", kcalPer100g: 205, category: "Pesce" },
  { name: "Sardine (al naturale)", kcalPer100g: 135, category: "Pesce" },
  { name: "Acciughe sott'olio", kcalPer100g: 210, category: "Pesce" },
  { name: "Trota", kcalPer100g: 119, category: "Pesce" },
  { name: "Pesce spada", kcalPer100g: 109, category: "Pesce" },
  { name: "Gamberi", kcalPer100g: 83, category: "Pesce" },
  { name: "Calamari", kcalPer100g: 92, category: "Pesce" },
  { name: "Polpo", kcalPer100g: 82, category: "Pesce" },
  { name: "Cozze", kcalPer100g: 84, category: "Pesce" },
  { name: "Vongole", kcalPer100g: 74, category: "Pesce" },
  { name: "Seppia", kcalPer100g: 79, category: "Pesce" },
  { name: "Baccalà (dissalato)", kcalPer100g: 94, category: "Pesce" },
  // Latticini e formaggi
  { name: "Latte intero", kcalPer100g: 64, category: "Latticini" },
  { name: "Latte parzialmente scremato", kcalPer100g: 46, category: "Latticini" },
  { name: "Latte scremato", kcalPer100g: 35, category: "Latticini" },
  { name: "Latte senza lattosio", kcalPer100g: 64, category: "Latticini" },
  { name: "Yogurt intero (bianco)", kcalPer100g: 62, category: "Latticini" },
  { name: "Yogurt greco", kcalPer100g: 97, category: "Latticini" },
  { name: "Yogurt greco 0%", kcalPer100g: 57, category: "Latticini" },
  { name: "Yogurt 0% grassi", kcalPer100g: 43, category: "Latticini" },
  { name: "Mozzarella", kcalPer100g: 253, category: "Latticini" },
  { name: "Fiordilatte", kcalPer100g: 242, category: "Latticini" },
  { name: "Parmigiano Reggiano", kcalPer100g: 431, category: "Latticini" },
  { name: "Grana Padano", kcalPer100g: 384, category: "Latticini" },
  { name: "Pecorino Romano", kcalPer100g: 387, category: "Latticini" },
  { name: "Gorgonzola", kcalPer100g: 313, category: "Latticini" },
  { name: "Stracchino", kcalPer100g: 252, category: "Latticini" },
  { name: "Scamorza", kcalPer100g: 295, category: "Latticini" },
  { name: "Provolone", kcalPer100g: 352, category: "Latticini" },
  { name: "Asiago", kcalPer100g: 352, category: "Latticini" },
  { name: "Emmental", kcalPer100g: 380, category: "Latticini" },
  { name: "Ricotta (vaccina)", kcalPer100g: 136, category: "Latticini" },
  { name: "Ricotta di pecora", kcalPer100g: 157, category: "Latticini" },
  { name: "Mascarpone", kcalPer100g: 429, category: "Latticini" },
  { name: "Panna da cucina", kcalPer100g: 190, category: "Latticini" },
  { name: "Panna montata", kcalPer100g: 257, category: "Latticini" },
  { name: "Burro", kcalPer100g: 758, category: "Latticini" },
  // Uova
  { name: "Uovo intero (medio)", kcalPer100g: 155, category: "Uova" },
  { name: "Albume d'uovo", kcalPer100g: 50, category: "Uova" },
  { name: "Tuorlo d'uovo", kcalPer100g: 352, category: "Uova" },
  { name: "Uova strapazzate (con burro)", kcalPer100g: 148, category: "Uova" },
  { name: "Frittata (uova e olio)", kcalPer100g: 164, category: "Uova" },
  // Legumi
  { name: "Ceci (cotti)", kcalPer100g: 164, category: "Legumi" },
  { name: "Ceci (in scatola)", kcalPer100g: 119, category: "Legumi" },
  { name: "Lenticchie (cotte)", kcalPer100g: 116, category: "Legumi" },
  { name: "Fagioli cannellini (cotti)", kcalPer100g: 127, category: "Legumi" },
  { name: "Fagioli borlotti (cotti)", kcalPer100g: 120, category: "Legumi" },
  { name: "Piselli (cotti)", kcalPer100g: 80, category: "Legumi" },
  { name: "Fave (cotte)", kcalPer100g: 72, category: "Legumi" },
  { name: "Soia (cotta)", kcalPer100g: 141, category: "Legumi" },
  { name: "Lupini", kcalPer100g: 114, category: "Legumi" },
  { name: "Tofu", kcalPer100g: 76, category: "Legumi" },
  { name: "Tempeh", kcalPer100g: 193, category: "Legumi" },
  { name: "Edamame", kcalPer100g: 122, category: "Legumi" },
  { name: "Hummus", kcalPer100g: 170, category: "Legumi" },
  // Verdure
  { name: "Insalata mista", kcalPer100g: 13, category: "Verdure" },
  { name: "Lattuga", kcalPer100g: 15, category: "Verdure" },
  { name: "Rucola", kcalPer100g: 25, category: "Verdure" },
  { name: "Radicchio", kcalPer100g: 23, category: "Verdure" },
  { name: "Spinaci", kcalPer100g: 23, category: "Verdure" },
  { name: "Cavolo cappuccio", kcalPer100g: 25, category: "Verdure" },
  { name: "Cavolo nero", kcalPer100g: 35, category: "Verdure" },
  { name: "Cavolo verza", kcalPer100g: 27, category: "Verdure" },
  { name: "Cavolfiore", kcalPer100g: 25, category: "Verdure" },
  { name: "Broccoli", kcalPer100g: 34, category: "Verdure" },
  { name: "Cime di rapa", kcalPer100g: 22, category: "Verdure" },
  { name: "Bietola", kcalPer100g: 20, category: "Verdure" },
  { name: "Indivia", kcalPer100g: 17, category: "Verdure" },
  { name: "Pomodori", kcalPer100g: 18, category: "Verdure" },
  { name: "Pomodorini", kcalPer100g: 20, category: "Verdure" },
  { name: "Zucchine", kcalPer100g: 16, category: "Verdure" },
  { name: "Melanzane", kcalPer100g: 24, category: "Verdure" },
  { name: "Peperoni", kcalPer100g: 27, category: "Verdure" },
  { name: "Cetrioli", kcalPer100g: 16, category: "Verdure" },
  { name: "Finocchio", kcalPer100g: 19, category: "Verdure" },
  { name: "Sedano", kcalPer100g: 14, category: "Verdure" },
  { name: "Carote", kcalPer100g: 35, category: "Verdure" },
  { name: "Patate", kcalPer100g: 77, category: "Verdure" },
  { name: "Patate dolci", kcalPer100g: 86, category: "Verdure" },
  { name: "Zucca", kcalPer100g: 26, category: "Verdure" },
  { name: "Cipolla", kcalPer100g: 38, category: "Verdure" },
  { name: "Cipollotto", kcalPer100g: 30, category: "Verdure" },
  { name: "Porro", kcalPer100g: 31, category: "Verdure" },
  { name: "Aglio", kcalPer100g: 149, category: "Verdure" },
  { name: "Asparagi", kcalPer100g: 20, category: "Verdure" },
  { name: "Funghi champignon", kcalPer100g: 22, category: "Verdure" },
  { name: "Funghi porcini", kcalPer100g: 27, category: "Verdure" },
  { name: "Fagiolini", kcalPer100g: 31, category: "Verdure" },
  { name: "Mais", kcalPer100g: 86, category: "Verdure" },
  { name: "Barbabietola", kcalPer100g: 43, category: "Verdure" },
  { name: "Topinambur", kcalPer100g: 73, category: "Verdure" },
  { name: "Carciofi", kcalPer100g: 47, category: "Verdure" },
  // Frutta
  { name: "Mela", kcalPer100g: 52, category: "Frutta" },
  { name: "Pera", kcalPer100g: 57, category: "Frutta" },
  { name: "Banana", kcalPer100g: 89, category: "Frutta" },
  { name: "Arancia", kcalPer100g: 47, category: "Frutta" },
  { name: "Mandarino", kcalPer100g: 53, category: "Frutta" },
  { name: "Limone", kcalPer100g: 29, category: "Frutta" },
  { name: "Pompelmo", kcalPer100g: 42, category: "Frutta" },
  { name: "Fragole", kcalPer100g: 32, category: "Frutta" },
  { name: "Lamponi", kcalPer100g: 52, category: "Frutta" },
  { name: "Mirtilli", kcalPer100g: 57, category: "Frutta" },
  { name: "Uva", kcalPer100g: 67, category: "Frutta" },
  { name: "Pesca", kcalPer100g: 39, category: "Frutta" },
  { name: "Albicocca", kcalPer100g: 48, category: "Frutta" },
  { name: "Prugna", kcalPer100g: 46, category: "Frutta" },
  { name: "Ciliegie", kcalPer100g: 63, category: "Frutta" },
  { name: "Kiwi", kcalPer100g: 61, category: "Frutta" },
  { name: "Avocado", kcalPer100g: 160, category: "Frutta" },
  { name: "Anguria", kcalPer100g: 30, category: "Frutta" },
  { name: "Melone", kcalPer100g: 34, category: "Frutta" },
  { name: "Ananas", kcalPer100g: 50, category: "Frutta" },
  { name: "Mango", kcalPer100g: 60, category: "Frutta" },
  { name: "Papaya", kcalPer100g: 43, category: "Frutta" },
  { name: "Fico", kcalPer100g: 74, category: "Frutta" },
  { name: "Melograno", kcalPer100g: 83, category: "Frutta" },
  { name: "Cachi", kcalPer100g: 65, category: "Frutta" },
  { name: "Castagne", kcalPer100g: 213, category: "Frutta" },
  { name: "Datteri", kcalPer100g: 282, category: "Frutta" },
  // Frutta secca e semi
  { name: "Noci", kcalPer100g: 654, category: "Frutta secca" },
  { name: "Mandorle", kcalPer100g: 578, category: "Frutta secca" },
  { name: "Arachidi", kcalPer100g: 567, category: "Frutta secca" },
  { name: "Anacardi", kcalPer100g: 553, category: "Frutta secca" },
  { name: "Pistacchi", kcalPer100g: 560, category: "Frutta secca" },
  { name: "Nocciole", kcalPer100g: 628, category: "Frutta secca" },
  { name: "Noci brasiliane", kcalPer100g: 659, category: "Frutta secca" },
  { name: "Pinoli", kcalPer100g: 673, category: "Frutta secca" },
  { name: "Semi di girasole", kcalPer100g: 584, category: "Frutta secca" },
  { name: "Semi di zucca", kcalPer100g: 559, category: "Frutta secca" },
  { name: "Semi di chia", kcalPer100g: 486, category: "Frutta secca" },
  { name: "Semi di lino", kcalPer100g: 534, category: "Frutta secca" },
  { name: "Semi di sesamo", kcalPer100g: 573, category: "Frutta secca" },
  // Grassi e condimenti
  { name: "Olio extravergine d'oliva", kcalPer100g: 884, category: "Condimenti" },
  { name: "Olio di semi", kcalPer100g: 884, category: "Condimenti" },
  { name: "Olio di cocco", kcalPer100g: 892, category: "Condimenti" },
  { name: "Maionese", kcalPer100g: 691, category: "Condimenti" },
  { name: "Maionese light", kcalPer100g: 330, category: "Condimenti" },
  { name: "Pesto alla genovese", kcalPer100g: 370, category: "Condimenti" },
  { name: "Burro di arachidi", kcalPer100g: 588, category: "Condimenti" },
  { name: "Tahini", kcalPer100g: 595, category: "Condimenti" },
  { name: "Ketchup", kcalPer100g: 112, category: "Condimenti" },
  { name: "Senape", kcalPer100g: 66, category: "Condimenti" },
  { name: "Salsa di soia", kcalPer100g: 60, category: "Condimenti" },
  { name: "Aceto balsamico", kcalPer100g: 88, category: "Condimenti" },
  { name: "Passata di pomodoro", kcalPer100g: 32, category: "Condimenti" },
  { name: "Concentrato di pomodoro", kcalPer100g: 82, category: "Condimenti" },
  { name: "Salsa worcestershire", kcalPer100g: 78, category: "Condimenti" },
  { name: "Zucchero bianco", kcalPer100g: 387, category: "Condimenti" },
  { name: "Zucchero di canna", kcalPer100g: 380, category: "Condimenti" },
  { name: "Miele", kcalPer100g: 304, category: "Condimenti" },
  { name: "Sciroppo d'acero", kcalPer100g: 260, category: "Condimenti" },
  // Dolci e snack
  { name: "Cioccolato fondente", kcalPer100g: 556, category: "Dolci" },
  { name: "Cioccolato al latte", kcalPer100g: 535, category: "Dolci" },
  { name: "Cioccolato bianco", kcalPer100g: 539, category: "Dolci" },
  { name: "Nutella", kcalPer100g: 539, category: "Dolci" },
  { name: "Gelato (panna)", kcalPer100g: 207, category: "Dolci" },
  { name: "Gelato (cioccolato)", kcalPer100g: 216, category: "Dolci" },
  { name: "Gelato (frutta)", kcalPer100g: 110, category: "Dolci" },
  { name: "Chips di patate", kcalPer100g: 536, category: "Dolci" },
  { name: "Barretta proteica", kcalPer100g: 350, category: "Dolci" },
  { name: "Biscotti secchi", kcalPer100g: 447, category: "Dolci" },
  { name: "Biscotti integrali", kcalPer100g: 390, category: "Dolci" },
  { name: "Wafer", kcalPer100g: 521, category: "Dolci" },
  { name: "Cornetto vuoto", kcalPer100g: 375, category: "Dolci" },
  { name: "Brioche", kcalPer100g: 352, category: "Dolci" },
  { name: "Muffin", kcalPer100g: 377, category: "Dolci" },
  { name: "Torta di mele", kcalPer100g: 265, category: "Dolci" },
  { name: "Crostata", kcalPer100g: 390, category: "Dolci" },
  { name: "Tiramisù", kcalPer100g: 280, category: "Dolci" },
  { name: "Cannolo (siciliano)", kcalPer100g: 360, category: "Dolci" },
  { name: "Merendina (pan di spagna)", kcalPer100g: 350, category: "Dolci" },
  { name: "Popcorn (senza burro)", kcalPer100g: 375, category: "Dolci" },
  { name: "Ciambella", kcalPer100g: 380, category: "Dolci" },
  // Bevande
  { name: "Latte di mandorla", kcalPer100g: 24, category: "Bevande" },
  { name: "Latte di soia", kcalPer100g: 33, category: "Bevande" },
  { name: "Latte di avena", kcalPer100g: 46, category: "Bevande" },
  { name: "Latte di cocco (da bere)", kcalPer100g: 20, category: "Bevande" },
  { name: "Succo d'arancia", kcalPer100g: 44, category: "Bevande" },
  { name: "Succo di mela", kcalPer100g: 46, category: "Bevande" },
  { name: "Succo di pomodoro", kcalPer100g: 17, category: "Bevande" },
  { name: "Caffè espresso", kcalPer100g: 2, category: "Bevande" },
  { name: "Tè (senza zucchero)", kcalPer100g: 1, category: "Bevande" },
  { name: "Coca Cola", kcalPer100g: 42, category: "Bevande" },
  { name: "Coca Cola Zero", kcalPer100g: 1, category: "Bevande" },
  { name: "Acqua di cocco", kcalPer100g: 19, category: "Bevande" },
  { name: "Birra (5%)", kcalPer100g: 43, category: "Bevande" },
  { name: "Vino rosso", kcalPer100g: 85, category: "Bevande" },
  { name: "Vino bianco", kcalPer100g: 70, category: "Bevande" },
  // Piatti pronti e altro
  { name: "Brodo di pollo", kcalPer100g: 15, category: "Altro" },
  { name: "Brodo vegetale", kcalPer100g: 10, category: "Altro" },
  { name: "Minestra di verdure", kcalPer100g: 35, category: "Altro" },
  { name: "Zuppa di legumi", kcalPer100g: 80, category: "Altro" },
  { name: "Proteine whey (polvere)", kcalPer100g: 370, category: "Altro" },
  { name: "Proteine caseine (polvere)", kcalPer100g: 360, category: "Altro" },
];
