export type FoodItem = { name: string; kcalPer100g: number; category: string };

export const FOODS: FoodItem[] = [
  // Cereali
  { name: "Pasta (cruda)", kcalPer100g: 353, category: "Cereali" },
  { name: "Pasta (cotta)", kcalPer100g: 131, category: "Cereali" },
  { name: "Riso (crudo)", kcalPer100g: 360, category: "Cereali" },
  { name: "Riso (cotto)", kcalPer100g: 130, category: "Cereali" },
  { name: "Pane bianco", kcalPer100g: 267, category: "Cereali" },
  { name: "Pane integrale", kcalPer100g: 247, category: "Cereali" },
  { name: "Crackers", kcalPer100g: 432, category: "Cereali" },
  { name: "Fette biscottate", kcalPer100g: 383, category: "Cereali" },
  { name: "Corn flakes", kcalPer100g: 370, category: "Cereali" },
  { name: "Fiocchi d'avena", kcalPer100g: 379, category: "Cereali" },
  { name: "Muesli", kcalPer100g: 365, category: "Cereali" },
  { name: "Pizza margherita", kcalPer100g: 271, category: "Cereali" },
  { name: "Cous cous (cotto)", kcalPer100g: 112, category: "Cereali" },
  // Carne
  { name: "Petto di pollo", kcalPer100g: 110, category: "Carne" },
  { name: "Coscia di pollo", kcalPer100g: 200, category: "Carne" },
  { name: "Petto di tacchino", kcalPer100g: 104, category: "Carne" },
  { name: "Manzo (bistecca)", kcalPer100g: 217, category: "Carne" },
  { name: "Macinato di manzo", kcalPer100g: 254, category: "Carne" },
  { name: "Prosciutto cotto", kcalPer100g: 215, category: "Carne" },
  { name: "Prosciutto crudo", kcalPer100g: 259, category: "Carne" },
  { name: "Bresaola", kcalPer100g: 175, category: "Carne" },
  { name: "Salame", kcalPer100g: 336, category: "Carne" },
  { name: "Salsiccia", kcalPer100g: 305, category: "Carne" },
  { name: "Pancetta", kcalPer100g: 337, category: "Carne" },
  // Pesce
  { name: "Tonno in scatola (al naturale)", kcalPer100g: 103, category: "Pesce" },
  { name: "Salmone", kcalPer100g: 208, category: "Pesce" },
  { name: "Orata", kcalPer100g: 121, category: "Pesce" },
  { name: "Merluzzo", kcalPer100g: 82, category: "Pesce" },
  { name: "Gamberi", kcalPer100g: 83, category: "Pesce" },
  { name: "Branzino", kcalPer100g: 97, category: "Pesce" },
  { name: "Sgombro", kcalPer100g: 205, category: "Pesce" },
  // Latticini
  { name: "Latte intero", kcalPer100g: 64, category: "Latticini" },
  { name: "Latte scremato", kcalPer100g: 35, category: "Latticini" },
  { name: "Yogurt intero (bianco)", kcalPer100g: 62, category: "Latticini" },
  { name: "Yogurt greco", kcalPer100g: 97, category: "Latticini" },
  { name: "Yogurt 0% grassi", kcalPer100g: 43, category: "Latticini" },
  { name: "Mozzarella", kcalPer100g: 253, category: "Latticini" },
  { name: "Parmigiano Reggiano", kcalPer100g: 431, category: "Latticini" },
  { name: "Grana Padano", kcalPer100g: 384, category: "Latticini" },
  { name: "Ricotta (vaccina)", kcalPer100g: 136, category: "Latticini" },
  { name: "Burro", kcalPer100g: 758, category: "Latticini" },
  // Uova
  { name: "Uovo intero (medio)", kcalPer100g: 155, category: "Uova" },
  { name: "Albume d'uovo", kcalPer100g: 50, category: "Uova" },
  { name: "Tuorlo d'uovo", kcalPer100g: 352, category: "Uova" },
  // Legumi
  { name: "Ceci (cotti)", kcalPer100g: 164, category: "Legumi" },
  { name: "Lenticchie (cotte)", kcalPer100g: 116, category: "Legumi" },
  { name: "Fagioli (cotti)", kcalPer100g: 127, category: "Legumi" },
  { name: "Piselli", kcalPer100g: 80, category: "Legumi" },
  { name: "Tofu", kcalPer100g: 76, category: "Legumi" },
  { name: "Edamame", kcalPer100g: 122, category: "Legumi" },
  // Verdure
  { name: "Insalata mista", kcalPer100g: 13, category: "Verdure" },
  { name: "Pomodori", kcalPer100g: 18, category: "Verdure" },
  { name: "Pomodorini", kcalPer100g: 20, category: "Verdure" },
  { name: "Zucchine", kcalPer100g: 16, category: "Verdure" },
  { name: "Carote", kcalPer100g: 35, category: "Verdure" },
  { name: "Broccoli", kcalPer100g: 34, category: "Verdure" },
  { name: "Spinaci", kcalPer100g: 23, category: "Verdure" },
  { name: "Peperoni", kcalPer100g: 27, category: "Verdure" },
  { name: "Cipolla", kcalPer100g: 38, category: "Verdure" },
  { name: "Patate", kcalPer100g: 77, category: "Verdure" },
  { name: "Patate dolci", kcalPer100g: 86, category: "Verdure" },
  { name: "Asparagi", kcalPer100g: 20, category: "Verdure" },
  { name: "Melanzane", kcalPer100g: 24, category: "Verdure" },
  { name: "Cetrioli", kcalPer100g: 16, category: "Verdure" },
  { name: "Funghi champignon", kcalPer100g: 22, category: "Verdure" },
  { name: "Cavolfiore", kcalPer100g: 25, category: "Verdure" },
  // Frutta
  { name: "Mela", kcalPer100g: 52, category: "Frutta" },
  { name: "Banana", kcalPer100g: 89, category: "Frutta" },
  { name: "Arancia", kcalPer100g: 47, category: "Frutta" },
  { name: "Fragole", kcalPer100g: 32, category: "Frutta" },
  { name: "Uva", kcalPer100g: 67, category: "Frutta" },
  { name: "Pesca", kcalPer100g: 39, category: "Frutta" },
  { name: "Kiwi", kcalPer100g: 61, category: "Frutta" },
  { name: "Avocado", kcalPer100g: 160, category: "Frutta" },
  { name: "Anguria", kcalPer100g: 30, category: "Frutta" },
  { name: "Ananas", kcalPer100g: 50, category: "Frutta" },
  { name: "Mango", kcalPer100g: 60, category: "Frutta" },
  { name: "Pera", kcalPer100g: 57, category: "Frutta" },
  { name: "Lamponi", kcalPer100g: 52, category: "Frutta" },
  { name: "Mirtilli", kcalPer100g: 57, category: "Frutta" },
  // Grassi e frutta secca
  { name: "Olio d'oliva", kcalPer100g: 884, category: "Grassi" },
  { name: "Olio di semi", kcalPer100g: 884, category: "Grassi" },
  { name: "Maionese", kcalPer100g: 691, category: "Grassi" },
  { name: "Pesto alla genovese", kcalPer100g: 370, category: "Grassi" },
  { name: "Noci", kcalPer100g: 654, category: "Grassi" },
  { name: "Mandorle", kcalPer100g: 578, category: "Grassi" },
  { name: "Arachidi", kcalPer100g: 567, category: "Grassi" },
  { name: "Burro di arachidi", kcalPer100g: 588, category: "Grassi" },
  // Dolci e snack
  { name: "Cioccolato fondente", kcalPer100g: 556, category: "Dolci" },
  { name: "Cioccolato al latte", kcalPer100g: 535, category: "Dolci" },
  { name: "Nutella", kcalPer100g: 539, category: "Dolci" },
  { name: "Gelato (panna)", kcalPer100g: 207, category: "Dolci" },
  { name: "Chips di patate", kcalPer100g: 536, category: "Dolci" },
  { name: "Barretta proteica", kcalPer100g: 350, category: "Dolci" },
  { name: "Biscotti secchi", kcalPer100g: 447, category: "Dolci" },
  // Bevande
  { name: "Latte di mandorla", kcalPer100g: 24, category: "Bevande" },
  { name: "Succo d'arancia", kcalPer100g: 44, category: "Bevande" },
  { name: "Zucchero", kcalPer100g: 387, category: "Bevande" },
  { name: "Miele", kcalPer100g: 304, category: "Bevande" },
];
